# Generated by Django 3.0.6 on 2020-06-16 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('user', models.OneToOneField(default='DEFAULT VALUE', editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('advRank', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('advCommission', models.DecimalField(decimal_places=3, max_digits=3)),
                ('balance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('boostId', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('boostType', models.CharField(choices=[('Dungeon', 'Dungeon'), ('Raid', 'Raid')], max_length=7)),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userRole', models.CharField(choices=[('User', 'User'), ('Advertiser', 'Advertiser'), ('Booster', 'Booster')], default='User', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('advertiser', models.OneToOneField(default='DEFAULT VALUE', editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BoostApp.Advertiser')),
                ('className', models.CharField(choices=[('Warrior', 'Warrior'), ('Paladin', 'Paladin'), ('Hunter', 'Hunter'), ('Rogue', 'Rogue'), ('Priest', 'Priest'), ('Shaman', 'Shaman'), ('Mage', 'Mage'), ('Warlock', 'Warlock'), ('Monk', 'Monk'), ('Druid', 'Druid'), ('Demon Hunter', 'Demon Hunter'), ('Death Knight', 'Death Knight')], max_length=12)),
                ('armourType', models.CharField(choices=[('Cloth', 'Cloth'), ('Leather', 'Leather'), ('Mail', 'Mail'), ('Plate', 'Plate')], max_length=7)),
                ('role', models.CharField(choices=[('Tank', 'Tank'), ('Healer', 'Healer'), ('Damage', 'Damage')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('buyer', models.CharField(max_length=30)),
                ('advertiser', models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='BoostApp.Advertiser')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('noOfBoosters', models.PositiveSmallIntegerField()),
                ('noOfBuyers', models.PositiveSmallIntegerField()),
                ('dateTime', models.DateTimeField()),
                ('totalPot', models.PositiveIntegerField()),
                ('advertiserCut', models.PositiveIntegerField()),
                ('boosterCut', models.PositiveIntegerField()),
                ('completed', models.BooleanField()),
                ('boost', models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='BoostApp.Boost')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTransaction',
            fields=[
                ('transaction', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BoostApp.Transaction')),
                ('booking', models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='BoostApp.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='BoostApp.Booking')),
                ('booster', models.ForeignKey(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, to='BoostApp.Booster')),
            ],
        ),
    ]
