# Generated by Django 3.0.6 on 2020-06-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoostApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='advRank',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
